-- ============================================================
-- DVD INVENTORY
-- INITIAL DATABASE + AUTHORIZATION ARCHITECTURE
-- ============================================================

begin;

-- ============================================================
-- PROFILES
-- ============================================================

create table if not exists public.profiles (
    id uuid primary key
        references auth.users(id)
        on delete cascade,

    username text not null unique,

    display_name text not null,

    role text not null default 'user'
        check (
            role in (
                'user',
                'admin'
            )
        ),

    active boolean not null default true,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- ============================================================
-- USER ADMINISTRATION AUDIT
-- ============================================================

create table if not exists public.user_admin_audit (
    id bigint generated by default as identity primary key,

    target_user_id uuid
        references auth.users(id)
        on delete set null,

    target_username text,

    action text not null
        check (
            action in (
                'user_created',
                'user_activated',
                'user_deactivated',
                'role_changed',
                'password_reset_requested'
            )
        ),

    old_value text,
    new_value text,

    performed_by uuid not null
        references auth.users(id),

    created_at timestamptz not null default now()
);

-- ============================================================
-- TOTES
-- ============================================================

create table if not exists public.totes (
    id bigint generated by default as identity primary key,

    tote_code text not null unique,

    description text,
    physical_location text,
    notes text,

    created_by uuid
        references auth.users(id),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- ============================================================
-- TITLES
-- ============================================================

create table if not exists public.titles (
    id bigint generated by default as identity primary key,

    title text not null,
    original_title text,

    year integer,

    imdb_id text,
    tmdb_id text,
    wikidata_id text,

    runtime_minutes integer,
    genres text,
    director text,
    plot text,
    poster_url text,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists titles_imdb_id_unique
    on public.titles(imdb_id)
    where imdb_id is not null;

-- ============================================================
-- PHYSICAL RELEASES
--
-- UPC IS TEXT.
-- DO NOT CHANGE IT TO A NUMBER.
-- ============================================================

create table if not exists public.physical_releases (
    id bigint generated by default as identity primary key,

    upc text not null unique,

    title_id bigint
        references public.titles(id)
        on delete set null,

    release_title text,
    edition text,
    format text,
    region text,

    studio text,
    distributor text,

    release_year integer,
    release_date date,

    aspect_ratio text,
    disc_count integer,
    packaging text,

    asin text,
    cover_image_url text,

    notes text,

    metadata_status text not null default 'unknown'
        check (
            metadata_status in (
                'unknown',
                'incomplete',
                'enriched',
                'verified',
                'needs_review'
            )
        ),

    created_by uuid
        references auth.users(id),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- ============================================================
-- INVENTORY
-- ============================================================

create table if not exists public.inventory (
    id bigint generated by default as identity primary key,

    tote_id bigint not null
        references public.totes(id)
        on delete restrict,

    physical_release_id bigint not null
        references public.physical_releases(id)
        on delete restrict,

    quantity integer not null default 0
        check (quantity >= 0),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    unique (
        tote_id,
        physical_release_id
    )
);

-- ============================================================
-- CHECKOUTS
-- ============================================================

create table if not exists public.checkouts (
    id bigint generated by default as identity primary key,

    physical_release_id bigint not null
        references public.physical_releases(id)
        on delete restrict,

    source_tote_id bigint not null
        references public.totes(id)
        on delete restrict,

    quantity integer not null
        check (quantity > 0),

    performed_by uuid not null
        references auth.users(id),

    checked_out_to text,
    destination text,
    notes text,

    checked_out_at timestamptz not null default now(),

    checked_in_at timestamptz,

    return_tote_id bigint
        references public.totes(id)
        on delete restrict,

    status text not null default 'checked_out'
        check (
            status in (
                'checked_out',
                'returned'
            )
        )
);

-- ============================================================
-- INVENTORY TRANSACTION HISTORY
-- ============================================================

create table if not exists public.inventory_transactions (
    id bigint generated by default as identity primary key,

    transaction_type text not null
        check (
            transaction_type in (
                'inventory_add',
                'inventory_remove',
                'checkout',
                'checkin',
                'transfer',
                'adjustment',
                'import'
            )
        ),

    physical_release_id bigint not null
        references public.physical_releases(id)
        on delete restrict,

    tote_id bigint
        references public.totes(id)
        on delete restrict,

    quantity_delta integer not null,

    checkout_id bigint
        references public.checkouts(id)
        on delete set null,

    performed_by uuid not null
        references auth.users(id),

    notes text,

    created_at timestamptz not null default now()
);

-- ============================================================
-- METADATA PROVENANCE
-- ============================================================

create table if not exists public.metadata_provenance (
    id bigint generated by default as identity primary key,

    physical_release_id bigint
        references public.physical_releases(id)
        on delete cascade,

    title_id bigint
        references public.titles(id)
        on delete cascade,

    field_name text not null,

    source text not null,

    source_record_id text,
    source_value text,

    manually_verified boolean not null default false,

    observed_at timestamptz not null default now(),

    check (
        physical_release_id is not null
        or title_id is not null
    )
);

-- ============================================================
-- ENRICHMENT QUEUE
-- ============================================================

create table if not exists public.enrichment_queue (
    id bigint generated by default as identity primary key,

    physical_release_id bigint not null
        references public.physical_releases(id)
        on delete cascade,

    status text not null default 'pending'
        check (
            status in (
                'pending',
                'processing',
                'completed',
                'partial',
                'failed'
            )
        ),

    attempts integer not null default 0,

    last_attempt_at timestamptz,
    next_attempt_at timestamptz,

    last_error text,

    created_at timestamptz not null default now(),
    completed_at timestamptz
);

-- ============================================================
-- SECURITY HELPER FUNCTIONS
-- ============================================================

create or replace function public.current_user_is_active()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
          and active = true
    );
$$;

create or replace function public.current_user_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
          and active = true
          and role = 'admin'
    );
$$;

create or replace function public.active_admin_count()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
    select count(*)
    from public.profiles
    where active = true
      and role = 'admin';
$$;

-- ============================================================
-- PROTECTED USER MANAGEMENT FUNCTION
--
-- Role/active changes MUST go through this function.
--
-- Protection:
--   - caller must be admin
--   - cannot alter own role
--   - cannot deactivate self
--   - cannot remove last active admin
-- ============================================================

create or replace function public.admin_update_user(
    target_user uuid,
    new_role text default null,
    new_active boolean default null
)
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
    caller uuid;
    old_profile public.profiles;
    updated_profile public.profiles;
begin

    caller := auth.uid();

    if caller is null then
        raise exception 'Authentication required.';
    end if;

    if not public.current_user_is_admin() then
        raise exception 'Administrator privileges required.';
    end if;

    select *
    into old_profile
    from public.profiles
    where id = target_user
    for update;

    if not found then
        raise exception 'User does not exist.';
    end if;

    if new_role is not null
       and new_role not in ('user', 'admin') then
        raise exception 'Invalid role.';
    end if;

    -- --------------------------------------------------------
    -- SELF-PROTECTION
    -- --------------------------------------------------------

    if target_user = caller then

        if new_active is false then
            raise exception
                'You cannot deactivate your own account.';
        end if;

        if new_role is not null
           and new_role <> old_profile.role then
            raise exception
                'You cannot change your own administrator role.';
        end if;

    end if;

    -- --------------------------------------------------------
    -- LAST ADMIN PROTECTION
    -- --------------------------------------------------------

    if old_profile.role = 'admin'
       and old_profile.active = true then

        if (
            new_role = 'user'
            or new_active is false
        ) then

            if public.active_admin_count() <= 1 then
                raise exception
                    'Cannot remove the final active administrator.';
            end if;

        end if;

    end if;

    -- --------------------------------------------------------
    -- ROLE AUDIT
    -- --------------------------------------------------------

    if new_role is not null
       and new_role <> old_profile.role then

        insert into public.user_admin_audit (
            target_user_id,
            target_username,
            action,
            old_value,
            new_value,
            performed_by
        )
        values (
            old_profile.id,
            old_profile.username,
            'role_changed',
            old_profile.role,
            new_role,
            caller
        );

    end if;

    -- --------------------------------------------------------
    -- ACTIVE STATUS AUDIT
    -- --------------------------------------------------------

    if new_active is not null
       and new_active <> old_profile.active then

        insert into public.user_admin_audit (
            target_user_id,
            target_username,
            action,
            old_value,
            new_value,
            performed_by
        )
        values (
            old_profile.id,
            old_profile.username,

            case
                when new_active
                    then 'user_activated'
                else 'user_deactivated'
            end,

            old_profile.active::text,
            new_active::text,

            caller
        );

    end if;

    update public.profiles
    set
        role = coalesce(
            new_role,
            role
        ),

        active = coalesce(
            new_active,
            active
        ),

        updated_at = now()

    where id = target_user

    returning *
    into updated_profile;

    return updated_profile;

end;
$$;

-- ============================================================
-- DATABASE-LEVEL GUARD
--
-- This protects against accidental direct profile changes
-- outside admin_update_user().
-- ============================================================

create or replace function public.protect_profile_security_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin

    if old.role is distinct from new.role
       or old.active is distinct from new.active then

        if not public.current_user_is_admin() then
            raise exception
                'Administrator privileges required.';
        end if;

        if old.id = auth.uid() then

            if old.role is distinct from new.role then
                raise exception
                    'You cannot change your own role.';
            end if;

            if new.active = false then
                raise exception
                    'You cannot deactivate your own account.';
            end if;

        end if;

        if old.role = 'admin'
           and old.active = true
           and (
               new.role <> 'admin'
               or new.active = false
           )
           and public.active_admin_count() <= 1 then

            raise exception
                'Cannot remove the final active administrator.';

        end if;

    end if;

    return new;

end;
$$;

drop trigger if exists
    protect_profile_security_fields_trigger
on public.profiles;

create trigger protect_profile_security_fields_trigger
before update
on public.profiles
for each row
execute function public.protect_profile_security_fields();

-- ============================================================
-- ENABLE RLS
-- ============================================================

alter table public.profiles
    enable row level security;

alter table public.user_admin_audit
    enable row level security;

alter table public.totes
    enable row level security;

alter table public.titles
    enable row level security;

alter table public.physical_releases
    enable row level security;

alter table public.inventory
    enable row level security;

alter table public.checkouts
    enable row level security;

alter table public.inventory_transactions
    enable row level security;

alter table public.metadata_provenance
    enable row level security;

alter table public.enrichment_queue
    enable row level security;

-- ============================================================
-- PROFILE RLS
-- ============================================================

drop policy if exists "profile_read_self_or_admin"
on public.profiles;

create policy "profile_read_self_or_admin"
on public.profiles
for select
to authenticated
using (
    id = auth.uid()
    or public.current_user_is_admin()
);

-- No direct profile INSERT/UPDATE/DELETE policy.
--
-- Security-sensitive modifications are performed through
-- protected server-side functions.

-- ============================================================
-- USER ADMIN AUDIT RLS
-- ============================================================

drop policy if exists "admin_read_user_audit"
on public.user_admin_audit;

create policy "admin_read_user_audit"
on public.user_admin_audit
for select
to authenticated
using (
    public.current_user_is_admin()
);

-- ============================================================
-- OPERATIONAL TABLE RLS
-- ============================================================

drop policy if exists "totes_active_users"
on public.totes;

create policy "totes_active_users"
on public.totes
for all
to authenticated
using (
    public.current_user_is_active()
)
with check (
    public.current_user_is_active()
);

drop policy if exists "titles_active_users"
on public.titles;

create policy "titles_active_users"
on public.titles
for all
to authenticated
using (
    public.current_user_is_active()
)
with check (
    public.current_user_is_active()
);

drop policy if exists "releases_active_users"
on public.physical_releases;

create policy "releases_active_users"
on public.physical_releases
for all
to authenticated
using (
    public.current_user_is_active()
)
with check (
    public.current_user_is_active()
);

drop policy if exists "inventory_active_users"
on public.inventory;

create policy "inventory_active_users"
on public.inventory
for all
to authenticated
using (
    public.current_user_is_active()
)
with check (
    public.current_user_is_active()
);

drop policy if exists "checkouts_active_users"
on public.checkouts;

create policy "checkouts_active_users"
on public.checkouts
for all
to authenticated
using (
    public.current_user_is_active()
)
with check (
    public.current_user_is_active()
);

-- ============================================================
-- TRANSACTION HISTORY
-- ============================================================

drop policy if exists "transactions_read"
on public.inventory_transactions;

create policy "transactions_read"
on public.inventory_transactions
for select
to authenticated
using (
    public.current_user_is_active()
);

drop policy if exists "transactions_insert"
on public.inventory_transactions;

create policy "transactions_insert"
on public.inventory_transactions
for insert
to authenticated
with check (
    public.current_user_is_active()
    and performed_by = auth.uid()
);

drop policy if exists "transactions_admin_update"
on public.inventory_transactions;

create policy "transactions_admin_update"
on public.inventory_transactions
for update
to authenticated
using (
    public.current_user_is_admin()
)
with check (
    public.current_user_is_admin()
);

drop policy if exists "transactions_admin_delete"
on public.inventory_transactions;

create policy "transactions_admin_delete"
on public.inventory_transactions
for delete
to authenticated
using (
    public.current_user_is_admin()
);

-- ============================================================
-- METADATA
-- ============================================================

drop policy if exists "metadata_read"
on public.metadata_provenance;

create policy "metadata_read"
on public.metadata_provenance
for select
to authenticated
using (
    public.current_user_is_active()
);

drop policy if exists "metadata_insert"
on public.metadata_provenance;

create policy "metadata_insert"
on public.metadata_provenance
for insert
to authenticated
with check (
    public.current_user_is_active()
);

drop policy if exists "metadata_admin_update"
on public.metadata_provenance;

create policy "metadata_admin_update"
on public.metadata_provenance
for update
to authenticated
using (
    public.current_user_is_admin()
)
with check (
    public.current_user_is_admin()
);

drop policy if exists "metadata_admin_delete"
on public.metadata_provenance;

create policy "metadata_admin_delete"
on public.metadata_provenance
for delete
to authenticated
using (
    public.current_user_is_admin()
);

-- ============================================================
-- ENRICHMENT QUEUE
-- ============================================================

drop policy if exists "enrichment_admin"
on public.enrichment_queue;

create policy "enrichment_admin"
on public.enrichment_queue
for all
to authenticated
using (
    public.current_user_is_admin()
)
with check (
    public.current_user_is_admin()
);

-- ============================================================
-- GRANTS
-- ============================================================

grant usage
on schema public
to authenticated;

grant select
on public.profiles
to authenticated;

grant select
on public.user_admin_audit
to authenticated;

grant select, insert, update, delete
on public.totes
to authenticated;

grant select, insert, update, delete
on public.titles
to authenticated;

grant select, insert, update, delete
on public.physical_releases
to authenticated;

grant select, insert, update, delete
on public.inventory
to authenticated;

grant select, insert, update, delete
on public.checkouts
to authenticated;

grant select, insert, update, delete
on public.inventory_transactions
to authenticated;

grant select, insert, update, delete
on public.metadata_provenance
to authenticated;

grant select, insert, update, delete
on public.enrichment_queue
to authenticated;

grant usage, select
on all sequences in schema public
to authenticated;

grant execute
on function public.current_user_is_active()
to authenticated;

grant execute
on function public.current_user_is_admin()
to authenticated;

grant execute
on function public.active_admin_count()
to authenticated;

grant execute
on function public.admin_update_user(uuid, text, boolean)
to authenticated;

-- ============================================================
-- ANONYMOUS USERS GET NOTHING
-- ============================================================

revoke all
on public.profiles
from anon;

revoke all
on public.user_admin_audit
from anon;

revoke all
on public.totes
from anon;

revoke all
on public.titles
from anon;

revoke all
on public.physical_releases
from anon;

revoke all
on public.inventory
from anon;

revoke all
on public.checkouts
from anon;

revoke all
on public.inventory_transactions
from anon;

revoke all
on public.metadata_provenance
from anon;

revoke all
on public.enrichment_queue
from anon;

commit;
