begin;

-- ============================================================
-- PRIVATE SECURITY SCHEMA
-- ============================================================

create schema if not exists private;

revoke all on schema private from public, anon, authenticated;
grant usage on schema private to authenticated;

-- ============================================================
-- APPLICATION TABLES
-- ============================================================

create table public.profiles (
    id uuid primary key references auth.users(id) on delete restrict,
    username text not null unique,
    display_name text not null,
    contact_email text,
    role text not null default 'user'
        check (role in ('user','admin')),
    active boolean not null default true,
    must_change_password boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.user_admin_audit (
    id bigint generated by default as identity primary key,
    target_user_id uuid references auth.users(id) on delete set null,
    target_username text,
    action text not null check (
        action in (
            'user_created',
            'user_activated',
            'user_deactivated',
            'role_changed',
            'password_reset_requested',
            'password_changed'
        )
    ),
    old_value text,
    new_value text,
    performed_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now()
);

create table public.totes (
    id bigint generated by default as identity primary key,
    tote_code text not null unique,
    description text,
    physical_location text,
    notes text,
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.titles (
    id bigint generated by default as identity primary key,
    title text not null,
    original_title text,
    year integer,
    imdb_id text,
    tmdb_id text,
    wikidata_id text,
    runtime_minutes integer,
    genres text,
    director text,
    plot text,
    poster_url text,
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index titles_imdb_id_unique
    on public.titles(imdb_id)
    where imdb_id is not null;

create table public.physical_releases (
    id bigint generated by default as identity primary key,

    -- UPC MUST REMAIN TEXT.
    upc text not null unique,

    title_id bigint references public.titles(id) on delete set null,
    release_title text,
    edition text,
    format text,
    region text,
    studio text,
    distributor text,
    release_year integer,
    release_date date,
    aspect_ratio text,
    disc_count integer,
    packaging text,
    asin text,
    cover_image_url text,
    notes text,

    metadata_status text not null default 'unknown'
        check (
            metadata_status in (
                'unknown',
                'incomplete',
                'enriched',
                'verified',
                'needs_review'
            )
        ),

    created_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.inventory (
    id bigint generated by default as identity primary key,
    tote_id bigint not null
        references public.totes(id) on delete restrict,
    physical_release_id bigint not null
        references public.physical_releases(id) on delete restrict,
    quantity integer not null default 0 check (quantity >= 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (tote_id, physical_release_id)
);

create table public.checkouts (
    id bigint generated by default as identity primary key,
    physical_release_id bigint not null
        references public.physical_releases(id) on delete restrict,
    source_tote_id bigint not null
        references public.totes(id) on delete restrict,
    quantity integer not null check (quantity > 0),

    performed_by uuid references auth.users(id) on delete set null,
    checked_out_to text,
    destination text,
    notes text,
    checked_out_at timestamptz not null default now(),

    checked_in_at timestamptz,
    return_tote_id bigint
        references public.totes(id) on delete restrict,
    checked_in_by uuid references auth.users(id) on delete set null,

    status text not null default 'checked_out'
        check (status in ('checked_out','returned')),

    check (
        (
            status = 'checked_out'
            and checked_in_at is null
            and return_tote_id is null
            and checked_in_by is null
        )
        or
        (
            status = 'returned'
            and checked_in_at is not null
            and return_tote_id is not null
            and checked_in_by is not null
        )
    )
);

create table public.inventory_transactions (
    id bigint generated by default as identity primary key,

    transaction_type text not null check (
        transaction_type in (
            'inventory_add',
            'inventory_remove',
            'checkout',
            'checkin',
            'transfer',
            'adjustment',
            'import'
        )
    ),

    physical_release_id bigint not null
        references public.physical_releases(id) on delete restrict,

    tote_id bigint
        references public.totes(id) on delete restrict,

    quantity_delta integer not null,

    checkout_id bigint
        references public.checkouts(id) on delete set null,

    performed_by uuid
        references auth.users(id) on delete set null,

    notes text,
    created_at timestamptz not null default now()
);

create index inventory_transactions_release_idx
    on public.inventory_transactions(physical_release_id);

create index inventory_transactions_tote_idx
    on public.inventory_transactions(tote_id);

create index inventory_transactions_created_idx
    on public.inventory_transactions(created_at);

create table public.metadata_provenance (
    id bigint generated by default as identity primary key,

    physical_release_id bigint
        references public.physical_releases(id) on delete cascade,

    title_id bigint
        references public.titles(id) on delete cascade,

    field_name text not null,
    source text not null,
    source_record_id text,
    source_value text,
    manually_verified boolean not null default false,
    observed_at timestamptz not null default now(),

    check (
        physical_release_id is not null
        or title_id is not null
    )
);

create table public.enrichment_queue (
    id bigint generated by default as identity primary key,

    physical_release_id bigint not null
        references public.physical_releases(id) on delete cascade,

    status text not null default 'pending'
        check (
            status in (
                'pending',
                'processing',
                'completed',
                'partial',
                'failed'
            )
        ),

    attempts integer not null default 0,
    last_attempt_at timestamptz,
    next_attempt_at timestamptz,
    last_error text,
    created_at timestamptz not null default now(),
    completed_at timestamptz
);

-- ============================================================
-- GENERIC TRIGGERS
-- ============================================================

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

create trigger profiles_updated_at
before update on public.profiles
for each row execute function private.set_updated_at();

create trigger totes_updated_at
before update on public.totes
for each row execute function private.set_updated_at();

create trigger titles_updated_at
before update on public.titles
for each row execute function private.set_updated_at();

create trigger releases_updated_at
before update on public.physical_releases
for each row execute function private.set_updated_at();

create trigger inventory_updated_at
before update on public.inventory
for each row execute function private.set_updated_at();

create or replace function private.force_created_by()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    if auth.uid() is null then
        raise exception 'Authentication required.';
    end if;

    new.created_by := auth.uid();
    return new;
end;
$$;

create trigger totes_created_by
before insert on public.totes
for each row execute function private.force_created_by();

create trigger titles_created_by
before insert on public.titles
for each row execute function private.force_created_by();

create trigger releases_created_by
before insert on public.physical_releases
for each row execute function private.force_created_by();

-- ============================================================
-- AUTHORIZATION HELPERS
-- ============================================================

create or replace function private.current_user_is_active()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
          and active = true
    );
$$;

create or replace function private.current_user_is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
          and active = true
          and role = 'admin'
    );
$$;

create or replace function private.require_active_user()
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
    caller uuid;
begin
    caller := auth.uid();

    if caller is null then
        raise exception 'Authentication required.';
    end if;

    if not private.current_user_is_active() then
        raise exception 'Active account required.';
    end if;

    return caller;
end;
$$;

-- ============================================================
-- ADMIN PROFILE MANAGEMENT
-- ============================================================

create or replace function public.admin_update_user(
    target_user uuid,
    new_role text default null,
    new_active boolean default null
)
returns public.profiles
language plpgsql
security definer
set search_path = ''
as $$
declare
    caller uuid;
    old_profile public.profiles;
    result public.profiles;
    admin_count bigint;
begin
    caller := auth.uid();

    if caller is null then
        raise exception 'Authentication required.';
    end if;

    if not private.current_user_is_admin() then
        raise exception 'Administrator privileges required.';
    end if;

    -- Serialize administrator-state changes.
    perform pg_catalog.pg_advisory_xact_lock(1480941637);

    select *
    into old_profile
    from public.profiles
    where id = target_user
    for update;

    if not found then
        raise exception 'User does not exist.';
    end if;

    if new_role is not null
       and new_role not in ('user','admin') then
        raise exception 'Invalid role.';
    end if;

    if target_user = caller then
        if new_active is false then
            raise exception 'You cannot deactivate your own account.';
        end if;

        if new_role is not null
           and new_role <> old_profile.role then
            raise exception 'You cannot change your own administrator role.';
        end if;
    end if;

    if old_profile.role = 'admin'
       and old_profile.active = true
       and (
            new_role = 'user'
            or new_active is false
       ) then

        select count(*)
        into admin_count
        from public.profiles
        where role = 'admin'
          and active = true;

        if admin_count <= 1 then
            raise exception 'Cannot remove the final active administrator.';
        end if;
    end if;

    if new_role is not null
       and new_role <> old_profile.role then

        insert into public.user_admin_audit (
            target_user_id,
            target_username,
            action,
            old_value,
            new_value,
            performed_by
        )
        values (
            old_profile.id,
            old_profile.username,
            'role_changed',
            old_profile.role,
            new_role,
            caller
        );
    end if;

    if new_active is not null
       and new_active <> old_profile.active then

        insert into public.user_admin_audit (
            target_user_id,
            target_username,
            action,
            old_value,
            new_value,
            performed_by
        )
        values (
            old_profile.id,
            old_profile.username,
            case
                when new_active then 'user_activated'
                else 'user_deactivated'
            end,
            old_profile.active::text,
            new_active::text,
            caller
        );
    end if;

    update public.profiles
    set
        role = coalesce(new_role, role),
        active = coalesce(new_active, active)
    where id = target_user
    returning *
    into result;

    return result;
end;
$$;

-- ============================================================
-- INVENTORY ADD
-- ============================================================

create or replace function public.inventory_add(
    p_tote_id bigint,
    p_physical_release_id bigint,
    p_quantity integer default 1,
    p_notes text default null
)
returns public.inventory
language plpgsql
security definer
set search_path = ''
as $$
declare
    caller uuid;
    result public.inventory;
begin
    caller := private.require_active_user();

    if p_quantity <= 0 then
        raise exception 'Quantity must be greater than zero.';
    end if;

    if not exists (
        select 1 from public.totes where id = p_tote_id
    ) then
        raise exception 'Tote does not exist.';
    end if;

    if not exists (
        select 1
        from public.physical_releases
        where id = p_physical_release_id
    ) then
        raise exception 'Physical release does not exist.';
    end if;

    insert into public.inventory (
        tote_id,
        physical_release_id,
        quantity
    )
    values (
        p_tote_id,
        p_physical_release_id,
        p_quantity
    )
    on conflict (tote_id, physical_release_id)
    do update
    set quantity =
        public.inventory.quantity + excluded.quantity
    returning *
    into result;

    insert into public.inventory_transactions (
        transaction_type,
        physical_release_id,
        tote_id,
        quantity_delta,
        performed_by,
        notes
    )
    values (
        'inventory_add',
        p_physical_release_id,
        p_tote_id,
        p_quantity,
        caller,
        p_notes
    );

    return result;
end;
$$;

-- ============================================================
-- INVENTORY REMOVE
-- ============================================================

create or replace function public.inventory_remove(
    p_tote_id bigint,
    p_physical_release_id bigint,
    p_quantity integer default 1,
    p_notes text default null
)
returns public.inventory
language plpgsql
security definer
set search_path = ''
as $$
declare
    caller uuid;
    result public.inventory;
begin
    caller := private.require_active_user();

    if p_quantity <= 0 then
        raise exception 'Quantity must be greater than zero.';
    end if;

    select *
    into result
    from public.inventory
    where tote_id = p_tote_id
      and physical_release_id = p_physical_release_id
    for update;

    if not found then
        raise exception 'Inventory record does not exist.';
    end if;

    if result.quantity < p_quantity then
        raise exception 'Insufficient inventory.';
    end if;

    update public.inventory
    set quantity = quantity - p_quantity
    where id = result.id
    returning *
    into result;

    insert into public.inventory_transactions (
        transaction_type,
        physical_release_id,
        tote_id,
        quantity_delta,
        performed_by,
        notes
    )
    values (
        'inventory_remove',
        p_physical_release_id,
        p_tote_id,
        -p_quantity,
        caller,
        p_notes
    );

    return result;
end;
$$;

-- ============================================================
-- INVENTORY TRANSFER
-- ============================================================

create or replace function public.inventory_transfer(
    p_source_tote_id bigint,
    p_destination_tote_id bigint,
    p_physical_release_id bigint,
    p_quantity integer default 1,
    p_notes text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    caller uuid;
    source_row public.inventory;
begin
    caller := private.require_active_user();

    if p_quantity <= 0 then
        raise exception 'Quantity must be greater than zero.';
    end if;

    if p_source_tote_id = p_destination_tote_id then
        raise exception 'Source and destination totes must differ.';
    end if;

    if not exists (
        select 1
        from public.totes
        where id = p_destination_tote_id
    ) then
        raise exception 'Destination tote does not exist.';
    end if;

    select *
    into source_row
    from public.inventory
    where tote_id = p_source_tote_id
      and physical_release_id = p_physical_release_id
    for update;

    if not found then
        raise exception 'Source inventory does not exist.';
    end if;

    if source_row.quantity < p_quantity then
        raise exception 'Insufficient inventory.';
    end if;

    update public.inventory
    set quantity = quantity - p_quantity
    where id = source_row.id;

    insert into public.inventory (
        tote_id,
        physical_release_id,
        quantity
    )
    values (
        p_destination_tote_id,
        p_physical_release_id,
        p_quantity
    )
    on conflict (tote_id, physical_release_id)
    do update
    set quantity =
        public.inventory.quantity + excluded.quantity;

    insert into public.inventory_transactions (
        transaction_type,
        physical_release_id,
        tote_id,
        quantity_delta,
        performed_by,
        notes
    )
    values
        (
            'transfer',
            p_physical_release_id,
            p_source_tote_id,
            -p_quantity,
            caller,
            p_notes
        ),
        (
            'transfer',
            p_physical_release_id,
            p_destination_tote_id,
            p_quantity,
            caller,
            p_notes
        );
end;
$$;

-- ============================================================
-- CHECK OUT
-- ============================================================

create or replace function public.checkout_inventory(
    p_source_tote_id bigint,
    p_physical_release_id bigint,
    p_quantity integer default 1,
    p_checked_out_to text default null,
    p_destination text default null,
    p_notes text default null
)
returns public.checkouts
language plpgsql
security definer
set search_path = ''
as $$
declare
    caller uuid;
    source_row public.inventory;
    result public.checkouts;
begin
    caller := private.require_active_user();

    if p_quantity <= 0 then
        raise exception 'Quantity must be greater than zero.';
    end if;

    select *
    into source_row
    from public.inventory
    where tote_id = p_source_tote_id
      and physical_release_id = p_physical_release_id
    for update;

    if not found then
        raise exception 'Inventory record does not exist.';
    end if;

    if source_row.quantity < p_quantity then
        raise exception 'Insufficient inventory.';
    end if;

    update public.inventory
    set quantity = quantity - p_quantity
    where id = source_row.id;

    insert into public.checkouts (
        physical_release_id,
        source_tote_id,
        quantity,
        performed_by,
        checked_out_to,
        destination,
        notes
    )
    values (
        p_physical_release_id,
        p_source_tote_id,
        p_quantity,
        caller,
        p_checked_out_to,
        p_destination,
        p_notes
    )
    returning *
    into result;

    insert into public.inventory_transactions (
        transaction_type,
        physical_release_id,
        tote_id,
        quantity_delta,
        checkout_id,
        performed_by,
        notes
    )
    values (
        'checkout',
        p_physical_release_id,
        p_source_tote_id,
        -p_quantity,
        result.id,
        caller,
        p_notes
    );

    return result;
end;
$$;

-- ============================================================
-- CHECK IN
-- ============================================================

create or replace function public.checkin_inventory(
    p_checkout_id bigint,
    p_return_tote_id bigint,
    p_notes text default null
)
returns public.checkouts
language plpgsql
security definer
set search_path = ''
as $$
declare
    caller uuid;
    result public.checkouts;
begin
    caller := private.require_active_user();

    if not exists (
        select 1
        from public.totes
        where id = p_return_tote_id
    ) then
        raise exception 'Return tote does not exist.';
    end if;

    select *
    into result
    from public.checkouts
    where id = p_checkout_id
    for update;

    if not found then
        raise exception 'Checkout does not exist.';
    end if;

    if result.status <> 'checked_out' then
        raise exception 'Checkout has already been returned.';
    end if;

    insert into public.inventory (
        tote_id,
        physical_release_id,
        quantity
    )
    values (
        p_return_tote_id,
        result.physical_release_id,
        result.quantity
    )
    on conflict (tote_id, physical_release_id)
    do update
    set quantity =
        public.inventory.quantity + excluded.quantity;

    update public.checkouts
    set
        status = 'returned',
        checked_in_at = now(),
        return_tote_id = p_return_tote_id,
        checked_in_by = caller,
        notes = case
            when p_notes is null then notes
            when notes is null then p_notes
            else notes || E'\n' || p_notes
        end
    where id = p_checkout_id
    returning *
    into result;

    insert into public.inventory_transactions (
        transaction_type,
        physical_release_id,
        tote_id,
        quantity_delta,
        checkout_id,
        performed_by,
        notes
    )
    values (
        'checkin',
        result.physical_release_id,
        p_return_tote_id,
        result.quantity,
        result.id,
        caller,
        p_notes
    );

    return result;
end;
$$;

-- ============================================================
-- ADMIN INVENTORY CORRECTION
-- ============================================================

create or replace function public.admin_adjust_inventory(
    p_tote_id bigint,
    p_physical_release_id bigint,
    p_new_quantity integer,
    p_notes text
)
returns public.inventory
language plpgsql
security definer
set search_path = ''
as $$
declare
    caller uuid;
    old_row public.inventory;
    result public.inventory;
    delta integer;
begin
    caller := auth.uid();

    if caller is null then
        raise exception 'Authentication required.';
    end if;

    if not private.current_user_is_admin() then
        raise exception 'Administrator privileges required.';
    end if;

    if p_new_quantity < 0 then
        raise exception 'Quantity cannot be negative.';
    end if;

    if p_notes is null or length(trim(p_notes)) = 0 then
        raise exception 'Adjustment reason is required.';
    end if;

    if not exists (
        select 1 from public.totes where id = p_tote_id
    ) then
        raise exception 'Tote does not exist.';
    end if;

    if not exists (
        select 1
        from public.physical_releases
        where id = p_physical_release_id
    ) then
        raise exception 'Physical release does not exist.';
    end if;

    select *
    into old_row
    from public.inventory
    where tote_id = p_tote_id
      and physical_release_id = p_physical_release_id
    for update;

    if found then
        delta := p_new_quantity - old_row.quantity;

        update public.inventory
        set quantity = p_new_quantity
        where id = old_row.id
        returning *
        into result;
    else
        delta := p_new_quantity;

        insert into public.inventory (
            tote_id,
            physical_release_id,
            quantity
        )
        values (
            p_tote_id,
            p_physical_release_id,
            p_new_quantity
        )
        returning *
        into result;
    end if;

    if delta <> 0 then
        insert into public.inventory_transactions (
            transaction_type,
            physical_release_id,
            tote_id,
            quantity_delta,
            performed_by,
            notes
        )
        values (
            'adjustment',
            p_physical_release_id,
            p_tote_id,
            delta,
            caller,
            p_notes
        );
    end if;

    return result;
end;
$$;

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table public.profiles enable row level security;
alter table public.user_admin_audit enable row level security;
alter table public.totes enable row level security;
alter table public.titles enable row level security;
alter table public.physical_releases enable row level security;
alter table public.inventory enable row level security;
alter table public.checkouts enable row level security;
alter table public.inventory_transactions enable row level security;
alter table public.metadata_provenance enable row level security;
alter table public.enrichment_queue enable row level security;

create policy profile_read_self_or_admin
on public.profiles for select to authenticated
using (
    id = auth.uid()
    or private.current_user_is_admin()
);

create policy user_admin_audit_read
on public.user_admin_audit for select to authenticated
using (private.current_user_is_admin());

create policy totes_read
on public.totes for select to authenticated
using (private.current_user_is_active());

create policy totes_insert
on public.totes for insert to authenticated
with check (private.current_user_is_active());

create policy totes_update
on public.totes for update to authenticated
using (private.current_user_is_active())
with check (private.current_user_is_active());

create policy titles_read
on public.titles for select to authenticated
using (private.current_user_is_active());

create policy titles_insert
on public.titles for insert to authenticated
with check (private.current_user_is_active());

create policy titles_update
on public.titles for update to authenticated
using (private.current_user_is_active())
with check (private.current_user_is_active());

create policy releases_read
on public.physical_releases for select to authenticated
using (private.current_user_is_active());

create policy releases_insert
on public.physical_releases for insert to authenticated
with check (private.current_user_is_active());

create policy releases_update
on public.physical_releases for update to authenticated
using (private.current_user_is_active())
with check (private.current_user_is_active());

create policy inventory_read
on public.inventory for select to authenticated
using (private.current_user_is_active());

create policy checkouts_read
on public.checkouts for select to authenticated
using (private.current_user_is_active());

create policy transactions_read
on public.inventory_transactions for select to authenticated
using (private.current_user_is_active());

create policy metadata_read
on public.metadata_provenance for select to authenticated
using (private.current_user_is_active());

create policy metadata_admin_insert
on public.metadata_provenance for insert to authenticated
with check (private.current_user_is_admin());

create policy metadata_admin_update
on public.metadata_provenance for update to authenticated
using (private.current_user_is_admin())
with check (private.current_user_is_admin());

create policy metadata_admin_delete
on public.metadata_provenance for delete to authenticated
using (private.current_user_is_admin());

create policy enrichment_admin_read
on public.enrichment_queue for select to authenticated
using (private.current_user_is_admin());

create policy enrichment_admin_insert
on public.enrichment_queue for insert to authenticated
with check (private.current_user_is_admin());

create policy enrichment_admin_update
on public.enrichment_queue for update to authenticated
using (private.current_user_is_admin())
with check (private.current_user_is_admin());

create policy enrichment_admin_delete
on public.enrichment_queue for delete to authenticated
using (private.current_user_is_admin());

-- ============================================================
-- TABLE PRIVILEGES
-- ============================================================

revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;

grant usage on schema public to authenticated;

grant select on public.profiles to authenticated;
grant select on public.user_admin_audit to authenticated;

-- Normal users may create catalog records, but UPDATE access is
-- intentionally limited to mutable business-data columns.
--
-- IDs, created_by, created_at, and updated_at are not directly
-- writable through UPDATE privileges.

grant select, insert
on public.totes
to authenticated;

grant update (
    tote_code,
    description,
    physical_location,
    notes
)
on public.totes
to authenticated;

grant select, insert
on public.titles
to authenticated;

grant update (
    title,
    original_title,
    year,
    imdb_id,
    tmdb_id,
    wikidata_id,
    runtime_minutes,
    genres,
    director,
    plot,
    poster_url
)
on public.titles
to authenticated;

grant select, insert
on public.physical_releases
to authenticated;

grant update (
    upc,
    title_id,
    release_title,
    edition,
    format,
    region,
    studio,
    distributor,
    release_year,
    release_date,
    aspect_ratio,
    disc_count,
    packaging,
    asin,
    cover_image_url,
    notes,
    metadata_status
)
on public.physical_releases
to authenticated;

grant select
on public.inventory,
   public.checkouts,
   public.inventory_transactions
to authenticated;

grant select, insert, update, delete
on public.metadata_provenance,
   public.enrichment_queue
to authenticated;

grant usage, select
on sequence public.totes_id_seq,
            public.titles_id_seq,
            public.physical_releases_id_seq,
            public.metadata_provenance_id_seq,
            public.enrichment_queue_id_seq
to authenticated;

-- ============================================================
-- FUNCTION PRIVILEGES
-- ============================================================

-- Remove PostgreSQL's default PUBLIC execute permission.
revoke all on function private.set_updated_at()
from public, anon, authenticated;

revoke all on function private.force_created_by()
from public, anon, authenticated;

revoke all on function private.current_user_is_active()
from public, anon, authenticated;

revoke all on function private.current_user_is_admin()
from public, anon, authenticated;

revoke all on function private.require_active_user()
from public, anon, authenticated;

-- RLS must be able to invoke these safe boolean predicates.
grant execute
on function private.current_user_is_active(),
            private.current_user_is_admin()
to authenticated;

-- require_active_user is called only from SECURITY DEFINER RPCs.
-- It remains unavailable as a direct client entry point.

revoke all
on function public.admin_update_user(uuid,text,boolean),
            public.inventory_add(bigint,bigint,integer,text),
            public.inventory_remove(bigint,bigint,integer,text),
            public.inventory_transfer(bigint,bigint,bigint,integer,text),
            public.checkout_inventory(bigint,bigint,integer,text,text,text),
            public.checkin_inventory(bigint,bigint,text),
            public.admin_adjust_inventory(bigint,bigint,integer,text)
from public, anon, authenticated;

grant execute
on function public.admin_update_user(uuid,text,boolean),
            public.inventory_add(bigint,bigint,integer,text),
            public.inventory_remove(bigint,bigint,integer,text),
            public.inventory_transfer(bigint,bigint,bigint,integer,text),
            public.checkout_inventory(bigint,bigint,integer,text,text,text),
            public.checkin_inventory(bigint,bigint,text),
            public.admin_adjust_inventory(bigint,bigint,integer,text)
to authenticated;

-- ============================================================
-- SAFE DEFAULTS FOR FUTURE OBJECTS
-- ============================================================

alter default privileges in schema public
revoke execute on functions from public;

alter default privileges in schema public
revoke all on tables from anon;

alter default privileges in schema public
revoke all on sequences from anon;

commit;