-- ============================================================
-- DVD Inventory
-- Initial database, authorization and RLS architecture
-- ============================================================

begin;


-- ------------------------------------------------------------
-- Profiles
-- ------------------------------------------------------------

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,

    username text not null unique,
    display_name text not null,

    role text not null default 'user'
        check (role in ('user', 'admin')),

    active boolean not null default true,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ------------------------------------------------------------
-- Totes
-- ------------------------------------------------------------

create table if not exists public.totes (
    id bigint generated by default as identity primary key,

    tote_code text not null unique,
    description text,
    physical_location text,
    notes text,

    created_by uuid references auth.users(id),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ------------------------------------------------------------
-- Titles
-- ------------------------------------------------------------

create table if not exists public.titles (
    id bigint generated by default as identity primary key,

    title text not null,
    original_title text,

    year integer,

    imdb_id text,
    tmdb_id text,
    wikidata_id text,

    runtime_minutes integer,
    genres text,
    director text,
    plot text,
    poster_url text,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


create unique index if not exists titles_imdb_id_unique
    on public.titles(imdb_id)
    where imdb_id is not null;


-- ------------------------------------------------------------
-- Physical releases
--
-- UPC MUST REMAIN TEXT.
-- ------------------------------------------------------------

create table if not exists public.physical_releases (
    id bigint generated by default as identity primary key,

    upc text not null unique,

    title_id bigint
        references public.titles(id)
        on delete set null,

    release_title text,
    edition text,
    format text,
    region text,

    studio text,
    distributor text,

    release_year integer,
    release_date date,

    aspect_ratio text,
    disc_count integer,
    packaging text,

    asin text,
    cover_image_url text,

    notes text,

    metadata_status text not null default 'unknown'
        check (
            metadata_status in (
                'unknown',
                'incomplete',
                'enriched',
                'verified',
                'needs_review'
            )
        ),

    created_by uuid references auth.users(id),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ------------------------------------------------------------
-- Inventory
-- ------------------------------------------------------------

create table if not exists public.inventory (
    id bigint generated by default as identity primary key,

    tote_id bigint not null
        references public.totes(id)
        on delete restrict,

    physical_release_id bigint not null
        references public.physical_releases(id)
        on delete restrict,

    quantity integer not null default 0
        check (quantity >= 0),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    unique (tote_id, physical_release_id)
);


-- ------------------------------------------------------------
-- Checkouts
-- ------------------------------------------------------------

create table if not exists public.checkouts (
    id bigint generated by default as identity primary key,

    physical_release_id bigint not null
        references public.physical_releases(id)
        on delete restrict,

    source_tote_id bigint not null
        references public.totes(id)
        on delete restrict,

    quantity integer not null
        check (quantity > 0),

    performed_by uuid not null
        references auth.users(id),

    checked_out_to text,
    destination text,
    notes text,

    checked_out_at timestamptz not null default now(),

    checked_in_at timestamptz,

    return_tote_id bigint
        references public.totes(id)
        on delete restrict,

    status text not null default 'checked_out'
        check (status in ('checked_out', 'returned'))
);


-- ------------------------------------------------------------
-- Inventory transaction / audit history
-- ------------------------------------------------------------

create table if not exists public.inventory_transactions (
    id bigint generated by default as identity primary key,

    transaction_type text not null
        check (
            transaction_type in (
                'inventory_add',
                'inventory_remove',
                'checkout',
                'checkin',
                'transfer',
                'adjustment',
                'import'
            )
        ),

    physical_release_id bigint not null
        references public.physical_releases(id)
        on delete restrict,

    tote_id bigint
        references public.totes(id)
        on delete restrict,

    quantity_delta integer not null,

    checkout_id bigint
        references public.checkouts(id)
        on delete set null,

    performed_by uuid not null
        references auth.users(id),

    notes text,

    created_at timestamptz not null default now()
);


-- ------------------------------------------------------------
-- Metadata provenance
-- ------------------------------------------------------------

create table if not exists public.metadata_provenance (
    id bigint generated by default as identity primary key,

    physical_release_id bigint
        references public.physical_releases(id)
        on delete cascade,

    title_id bigint
        references public.titles(id)
        on delete cascade,

    field_name text not null,
    source text not null,

    source_record_id text,
    source_value text,

    manually_verified boolean not null default false,

    observed_at timestamptz not null default now(),

    check (
        physical_release_id is not null
        or title_id is not null
    )
);


-- ------------------------------------------------------------
-- Enrichment queue
-- ------------------------------------------------------------

create table if not exists public.enrichment_queue (
    id bigint generated by default as identity primary key,

    physical_release_id bigint not null
        references public.physical_releases(id)
        on delete cascade,

    status text not null default 'pending'
        check (
            status in (
                'pending',
                'processing',
                'completed',
                'partial',
                'failed'
            )
        ),

    attempts integer not null default 0,

    last_attempt_at timestamptz,
    next_attempt_at timestamptz,

    last_error text,

    created_at timestamptz not null default now(),
    completed_at timestamptz
);


-- ------------------------------------------------------------
-- Helper functions
-- ------------------------------------------------------------

create or replace function public.current_user_is_active()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
          and active = true
    );
$$;


create or replace function public.current_user_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
          and active = true
          and role = 'admin'
    );
$$;


-- ------------------------------------------------------------
-- RLS
-- ------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.totes enable row level security;
alter table public.titles enable row level security;
alter table public.physical_releases enable row level security;
alter table public.inventory enable row level security;
alter table public.checkouts enable row level security;
alter table public.inventory_transactions enable row level security;
alter table public.metadata_provenance enable row level security;
alter table public.enrichment_queue enable row level security;


-- ------------------------------------------------------------
-- Profiles policies
-- ------------------------------------------------------------

drop policy if exists "profiles_read_self" on public.profiles;

create policy "profiles_read_self"
on public.profiles
for select
to authenticated
using (
    id = auth.uid()
    or public.current_user_is_admin()
);


drop policy if exists "profiles_admin_update" on public.profiles;

create policy "profiles_admin_update"
on public.profiles
for update
to authenticated
using (
    public.current_user_is_admin()
)
with check (
    public.current_user_is_admin()
);


-- ------------------------------------------------------------
-- Normal operational tables
--
-- Active authenticated users can operate DVD Inventory.
-- ------------------------------------------------------------

drop policy if exists "totes_active_users" on public.totes;

create policy "totes_active_users"
on public.totes
for all
to authenticated
using (
    public.current_user_is_active()
)
with check (
    public.current_user_is_active()
);


drop policy if exists "titles_active_users" on public.titles;

create policy "titles_active_users"
on public.titles
for all
to authenticated
using (
    public.current_user_is_active()
)
with check (
    public.current_user_is_active()
);


drop policy if exists "releases_active_users"
on public.physical_releases;

create policy "releases_active_users"
on public.physical_releases
for all
to authenticated
using (
    public.current_user_is_active()
)
with check (
    public.current_user_is_active()
);


drop policy if exists "inventory_active_users"
on public.inventory;

create policy "inventory_active_users"
on public.inventory
for all
to authenticated
using (
    public.current_user_is_active()
)
with check (
    public.current_user_is_active()
);


drop policy if exists "checkouts_active_users"
on public.checkouts;

create policy "checkouts_active_users"
on public.checkouts
for all
to authenticated
using (
    public.current_user_is_active()
)
with check (
    public.current_user_is_active()
);


-- ------------------------------------------------------------
-- Audit history
--
-- Users may read and insert history.
-- Existing history cannot be silently edited/deleted by normal users.
-- ------------------------------------------------------------

drop policy if exists "transactions_read"
on public.inventory_transactions;

create policy "transactions_read"
on public.inventory_transactions
for select
to authenticated
using (
    public.current_user_is_active()
);


drop policy if exists "transactions_insert"
on public.inventory_transactions;

create policy "transactions_insert"
on public.inventory_transactions
for insert
to authenticated
with check (
    public.current_user_is_active()
    and performed_by = auth.uid()
);


drop policy if exists "transactions_admin_update"
on public.inventory_transactions;

create policy "transactions_admin_update"
on public.inventory_transactions
for update
to authenticated
using (
    public.current_user_is_admin()
)
with check (
    public.current_user_is_admin()
);


drop policy if exists "transactions_admin_delete"
on public.inventory_transactions;

create policy "transactions_admin_delete"
on public.inventory_transactions
for delete
to authenticated
using (
    public.current_user_is_admin()
);


-- ------------------------------------------------------------
-- Metadata
-- ------------------------------------------------------------

drop policy if exists "metadata_read"
on public.metadata_provenance;

create policy "metadata_read"
on public.metadata_provenance
for select
to authenticated
using (
    public.current_user_is_active()
);


drop policy if exists "metadata_write"
on public.metadata_provenance;

create policy "metadata_write"
on public.metadata_provenance
for insert
to authenticated
with check (
    public.current_user_is_active()
);


drop policy if exists "metadata_admin_modify"
on public.metadata_provenance;

create policy "metadata_admin_modify"
on public.metadata_provenance
for update
to authenticated
using (
    public.current_user_is_admin()
)
with check (
    public.current_user_is_admin()
);


-- ------------------------------------------------------------
-- Enrichment administration
-- ------------------------------------------------------------

drop policy if exists "enrichment_admin"
on public.enrichment_queue;

create policy "enrichment_admin"
on public.enrichment_queue
for all
to authenticated
using (
    public.current_user_is_admin()
)
with check (
    public.current_user_is_admin()
);


-- ------------------------------------------------------------
-- Explicit API grants
-- ------------------------------------------------------------

grant usage on schema public to authenticated;

grant select on public.profiles to authenticated;
grant update on public.profiles to authenticated;

grant select, insert, update, delete
on public.totes
to authenticated;

grant select, insert, update, delete
on public.titles
to authenticated;

grant select, insert, update, delete
on public.physical_releases
to authenticated;

grant select, insert, update, delete
on public.inventory
to authenticated;

grant select, insert, update, delete
on public.checkouts
to authenticated;

grant select, insert, update, delete
on public.inventory_transactions
to authenticated;

grant select, insert, update, delete
on public.metadata_provenance
to authenticated;

grant select, insert, update, delete
on public.enrichment_queue
to authenticated;

grant usage, select
on all sequences in schema public
to authenticated;

grant execute
on function public.current_user_is_active()
to authenticated;

grant execute
on function public.current_user_is_admin()
to authenticated;


-- ------------------------------------------------------------
-- Keep anonymous visitors out.
-- No grants are given to anon.
-- ------------------------------------------------------------

revoke all on public.profiles from anon;
revoke all on public.totes from anon;
revoke all on public.titles from anon;
revoke all on public.physical_releases from anon;
revoke all on public.inventory from anon;
revoke all on public.checkouts from anon;
revoke all on public.inventory_transactions from anon;
revoke all on public.metadata_provenance from anon;
revoke all on public.enrichment_queue from anon;


commit;
